# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: UA-193192572-1
# disqus-ID: x
# utterances-repo: x

links:
  slack: https://www.hkubs.hku.hk/people/yang-you/

assets:
  logo: '/assets/site/lp-logo.svg'
  badge: '/assets/site/lp-badge-white.svg'

menu:
- {name: 'Home', file: '/tutorials.html'}
- {name: 'NFT Data', file: 'https://www.hkubs.hku.hk/people/yang-you/'}
- {name: 'Docs', file: '/platform'}
- {name: 'Contact Us', file: 'https://www.hkubs.hku.hk/people/yang-you/'}

social:
# - {name: 'slack', icon: 'fab fa-slack-hash', link: ''}
- {name: 'Github', icon: 'fab fa-github', link: 'https://www.hkubs.hku.hk/people/yang-you/'}

tutorials:
  categories:
    - {name: 'starter', title: 'Starter Example'}
    - {name: 'usecase', title: 'Use Cases'}

footnote: >
  Created and maintained by Layout Parser Developers. Built with [jekyll](https://jekyllrb.com/) and [bulma](http://bulma.io/).